= Red Hat Ansible Playground
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2023-12
// Metadata
:description: Play with Ansible plays and configuration of RHEL VMs.
:keywords: linux, rhel, ansible, red hat
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 3
:sectnums: 
:source-highlighter: pygments
:imagesdir: docs/images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]

// Create the Table of contents here
toc::[]

== Introduction

In this repo, I want to explore some of the basic Ansible features that allow you to manage your VMs.







== Setting up a local environment

.Manage the new VM
[source, bash]
----
kcli create plan -f docs/kcli-template-rhel92.yaml rhel92 # Create a basic plan with one VM
kcli plan -s rhel92 # Start the plan
kcli plan -w rhel92 # Stop the plan
kcli list vm        # Show VMs status
kcli plan -d rhel92 # Delete the plan
----

.Add the VM to the /etc/hosts
[source, bash]
----
sudo bash -c 'echo "192.168.122.100 rhel92.vm" >> /etc/hosts'
----

.Copy your ssh keys
[source, bash]
----
ssh-copy-id rhel92.vm
----


== Ansible Automation Platform

Red Hat Ansible Automation Platform is an end-to-end automation platform to configure systems, deploy software, and orchestrate advanced workflows.






=== Vi useful configuration

[source, console]
----
autocmd FileType yaml setlocal ai ts=2 sw=2 et
----


== Ansible basics

=== Get documentation

.List all the available modules
[source, bash]
----
# List available images
ansible-navigator images

# List available modules
ansible-navigator doc -l

# List available collections
ansible-navigator collections

# Get documentation for one module
ansible-navigator -s doc module_name

# Create a role from scratch
ansible-galaxy init alvaro.testing
----

.Autogenerate ansible config file with defaults
[source, bash]
----
ansible-navigator config init --disabled > ansible.cfg
----

.Autogenerate ansible-navigator YAML with defaults
[source, bash]
----
ansible-navigator settings --sample > ansible-navigator.yml
----




=== Ansible Vault


[source, bash]
----
# Create secret
ansible-vault create --vault-password-file=vault-pass.txt group_vars/web/vault.yml

# Edit Secret
ansible-vault edit --vault-password-file=vault-pass.txt group_vars/web/vault.yml

# Execute Plays with password
ansible-navigator run -m stdout --vault-password-file=vault-pass.txt plays/20_variables.yaml 
----


=== Gather Facts

[source, bash]
----
ansible-navigator run -m stdout plays/30_facts.yaml
----


=== Loops, Conditionals, and Handlers

[source, bash]
----
ansible-navigator run -m stdout --ask-become-pass plays/40_task_control.yaml
----


=== Manage Files

[source, bash]
----
ansible-navigator run -m stdout plays/50_deploy_files.yaml
----


=== Complex Plays

[source, bash]
----
ansible-navigator run -m stdout --ask-become-pass plays/60_complex_plays.yaml
----


=== Roles and Collections

.Install existing roles and collections
[source, bash]
----
# Install a Role
ansible-galaxy role install -r roles/requirements.yml

# Install a Collection
ansible-galaxy collection install -r collections/requirements.yml -p collections
----

KCS about System Roles availability and support: https://access.redhat.com/articles/3050101


[source, bash]
----
ansible-navigator run -m stdout --ask-become-pass plays/70_roles_and_collections.yaml
----









=== Manage Subscriptions

[source, bash]
----
ansible-navigator run -m stdout --ask-become-pass plays/90_rh_subs.yaml
----




TIP: I strongly recommend the exercises proposed by *mateuszstompor* in his repo https://github.com/mateuszstompor/rhce-ex294-exam/tree/main[rhce-ex294-exam]. He has some generic exercises that provide a good starting point to make sure that you control the topics that appear in the RHCE exam for RHEL 9.